package com.gradeflow.presentation.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFFFF6B6B)
val PrimaryVariantLight = Color(0xFFFF5252)
val SecondaryLight = Color(0xFFFFD6D6)
val BackgroundLight = Color(0xFFFFF8F8)
val SurfaceLight = Color(0xFFFFFFFF)
val OnPrimaryLight = Color(0xFFFFFFFF)
val OnSecondaryLight = Color(0xFF222222)
val OnBackgroundLight = Color(0xFF222222)
val OnSurfaceLight = Color(0xFF222222)
val ErrorLight = Color(0xFFE53935)
val OnErrorLight = Color(0xFFFFFFFF)
val OutlineLight = Color(0xFFFFE0E0)
val SurfaceVariantLight = Color(0xFFFFF0F0)
val TertiaryLight = Color(0xFFFF8A80)

val PrimaryDark = Color(0xFFFF8A8A)
val PrimaryVariantDark = Color(0xFFFF6B6B)
val SecondaryDark = Color(0xFF4D2C2C)
val BackgroundDark = Color(0xFF1A1A1A)
val SurfaceDark = Color(0xFF2D2222)
val OnPrimaryDark = Color(0xFF1A1A1A)
val OnSecondaryDark = Color(0xFFFFD6D6)
val OnBackgroundDark = Color(0xFFF5F5F5)
val OnSurfaceDark = Color(0xFFF5F5F5)
val ErrorDark = Color(0xFFFF6B6B)
val OnErrorDark = Color(0xFF1A1A1A)
val OutlineDark = Color(0xFF4D3333)
val SurfaceVariantDark = Color(0xFF3D2A2A)
val TertiaryDark = Color(0xFFFFABAB)

val GradeExcellent = Color(0xFF4CAF50)
val GradeGood = Color(0xFF8BC34A)
val GradeAverage = Color(0xFFFFC107)
val GradeBelowAverage = Color(0xFFFF9800)
val GradeFail = Color(0xFFE53935)
val CardBorder = Color(0xFFFFE8E8)
